baseURL = "https://bioimpedance-scale.vercel.app/"
defaultContentLanguage = "en"
languageCode = "en"

title = "Bioimpedance Scale Blog"

theme = ["gokarna"]

enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    
    pre = ""

    weight = 1

  [[menu.main]]
    identifier = "project"
    name = "Project"
    url = "/project/"
    
    pre = ""

    weight = 2

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    
    pre = ""

    weight = 3

  [[menu.main]]
    identifier = "schedule"
    name = "Schedule"
    url = "/schedule/"
    
    pre = ""

    weight = 4

  [[menu.main]]
    identifier = "team"
    name = "Team"
    url = "/team/"
    weight = 5
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/rjrobsonjunior/BioimpedanceScale_OF2"
    weight = 6
    
    pre = "<span data-feather='github'></span>"

[params]
  # URL for the avatar on homepage
  avatarURL = "/images/coconut.webp"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-l"

  # Description to display on homepage
  description = "Check your health from the comfort of your phone"

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#FF4D4D"

  # Display "back to top" button on posts
  ShowBackToTopButton = true

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["blog", "scale", "bioimpedance", "health"]

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  showPostsOnHomePage = ""
